# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProductListing' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProductListing

#📡 Network calls
  pod 'Alamofire'

  #🎭 Json conversion - avoids optinal chaining
  pod 'SwiftyJSON'
  
  target 'ProductListingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProductListingUITests' do
    # Pods for testing
  end

end
